 #### К практическому заданию 5

In [1]:
import numpy as np

In [3]:
a = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
np.linalg.det(a)

59.999999999999986

In [13]:
a1 = np.linalg.inv(a)
a1

array([[-0.8       ,  0.1       ,  0.2       ],
       [ 0.1       , -0.2       ,  0.1       ],
       [ 0.53333333,  0.1       , -0.13333333]])

In [4]:
np.linalg.matrix_rank(a, 0.0001)

3

2. Приведите пример матрицы 4х4, ранг которой равен 1.

In [9]:
c = np.array([[7, 8, 9, 0], [7, 8, 9, 0], [7, 8, 9, 0], [7, 8, 9, 0]])
c

array([[7, 8, 9, 0],
       [7, 8, 9, 0],
       [7, 8, 9, 0],
       [7, 8, 9, 0]])

In [10]:
np.linalg.matrix_rank(c, 0.0001)

1

 #### К практическому заданию 6

1. Решите линейную систему

In [14]:
A = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
A

array([[1, 2, 3],
       [4, 0, 6],
       [7, 8, 9]])

In [16]:
B = np.array([12, 2, 1])
B

array([12,  2,  1])

In [17]:
np.linalg.solve(A, B)

array([-9.2       ,  0.9       ,  6.46666667])

In [20]:
X = np.dot(np.linalg.inv(A), B)
X

array([-9.2       ,  0.9       ,  6.46666667])

2. Найдите псевдорешение

In [21]:
A = np.array([[1, 2, -2], [3, -4, 0], [8, -5, 2], [2, 0, -5], [11, 4, -7]])
A

array([[ 1,  2, -2],
       [ 3, -4,  0],
       [ 8, -5,  2],
       [ 2,  0, -5],
       [11,  4, -7]])

In [22]:
B = np.array([1, 7, 12, 7, 15])
B

array([ 1,  7, 12,  7, 15])

In [23]:
np.linalg.solve(A, B)

LinAlgError: Last 2 dimensions of the array must be square